package com.abstractdao;


/**
 * AbstractStudent generated by MyEclipse Persistence Tools
 */

public abstract class AbstractStudent implements java.io.Serializable {

	// Fields

	private Integer sid;
	private  String sname;
	private  Integer sage;
	private  String saddr;
	
	public AbstractStudent() {
		
	}
	
	
	public AbstractStudent(Integer sid) {
		this.sid = sid;
	}

	
	public AbstractStudent(Integer sid, String sname, Integer sage, String saddr) {
		this.sid = sid;
		this.sname = sname;
		this.sage = sage;
		this.saddr = saddr;
	}

	public Integer getSid() {
		return sid;
	}


	public void setSid(Integer sid) {
		this.sid = sid;
	}


	public String getSname() {
		return sname;
	}


	public void setSname(String sname) {
		this.sname = sname;
	}


	public Integer getSage() {
		return sage;
	}


	public void setSage(Integer sage) {
		this.sage = sage;
	}


	public String getSaddr() {
		return saddr;
	}


	public void setSaddr(String saddr) {
		this.saddr = saddr;
	}


	
}